/*
PROCEDURE RESPONSÁVEL POR REALIZAR OPERAÇÕES DE CRUD (CREATE, READ, UPDATE, DELETE) NA TABELA CAD_PESSOA.
AS OPERAÇÕES SÃO CONTROLADAS PELO PARÂMETRO @V_OPER, QUE DEFINE A AÇÃO A SER EXECUTADA:
[I] INSERE UM NOVO REGISTRO,
[S] CONSULTA UM REGISTRO,
[A] ATUALIZA UM REGISTRO EXISTENTE,
[D] DELETA UM REGISTRO.

A PROCEDURE INCLUI TRATAMENTO DE ERROS COM TRY...CATCH E CONTROLE DE TRANSAÇÕES PARA GARANTIR A CONSISTÊNCIA DOS DADOS.


CREATE TABLE CAD_PESSOA 
(
    ID_PESSOA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50),
    EMAIL VARCHAR(30),
    SITUACAO CHAR(1),
    CONSTRAINT CK_SITUA CHECK(SITUACAO IN('B','A'))
    );

*/


--DROP PROCEDURE CRUD

CREATE PROCEDURE CRUD
    @V_OPER CHAR(1), -- [I] INSERIR [A] ATUALIZAR [S] SELECIONAR [D] DELETAR
    @V_ID_PESSOA INT,
    @V_NOME VARCHAR(50),
    @V_EMAIL VARCHAR(30),
    @V_SITUACAO CHAR(1)
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION

        -- INSERIR
        IF (@V_OPER = 'I')
        BEGIN
            IF (@V_ID_PESSOA IS NULL OR @V_NOME IS NULL OR @V_EMAIL IS NULL)
            BEGIN
                THROW 50001, 'CAMPOS INCOMPLETOS PARA INSERÇÃO', 1;
            END

            INSERT INTO CAD_PESSOA (ID_PESSOA, NOME, EMAIL, SITUACAO)
            VALUES (@V_ID_PESSOA, @V_NOME, @V_EMAIL, 'A')
        END

        -- ATUALIZAR
        ELSE IF (@V_OPER = 'A')
        BEGIN
            IF (@V_ID_PESSOA IS NULL)
            BEGIN
                THROW 50002, 'ID OBRIGATÓRIO PARA ATUALIZAÇÃO', 1;
            END

            UPDATE CAD_PESSOA
            SET 
                NOME = ISNULL(@V_NOME, NOME),
                EMAIL = ISNULL(@V_EMAIL, EMAIL),
                SITUACAO = ISNULL(@V_SITUACAO, SITUACAO)
            WHERE ID_PESSOA = @V_ID_PESSOA
        END

        -- DELETAR
        ELSE IF (@V_OPER = 'D')
        BEGIN
            IF (@V_ID_PESSOA IS NULL)
            BEGIN
                THROW 50003, 'ID OBRIGATÓRIO PARA EXCLUSÃO', 1;
            END

            DELETE FROM CAD_PESSOA WHERE ID_PESSOA = @V_ID_PESSOA
        END

        -- SELECIONAR
        ELSE IF (@V_OPER = 'S')
        BEGIN
            SELECT
                @V_ID_PESSOA = A.ID_PESSOA,
                @V_NOME = A.NOME,
                @V_EMAIL = A.EMAIL,
                @V_SITUACAO = A.SITUACAO
            FROM CAD_PESSOA A
            WHERE ID_PESSOA = @V_ID_PESSOA

            PRINT '------ DADOS ------'
            PRINT 'ID = ' + CAST(@V_ID_PESSOA AS VARCHAR(10))
            PRINT 'NOME = ' + @V_NOME
            PRINT 'E-MAIL = ' + @V_EMAIL
            PRINT 'SITUACAO = ' + @V_SITUACAO
            PRINT '-------------------'
        END

        COMMIT
    END TRY

    BEGIN CATCH
        IF XACT_STATE() <> 0
            ROLLBACK TRANSACTION

        PRINT 'OCORREU UM ERRO: ' + ERROR_MESSAGE()
    END CATCH
END



-- INSERT
EXECUTE CRUD 'I', 1, 'ANA SILVA', 'ANA.SILVA@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 2, 'JOÃO PEREIRA', 'JOAO.PEREIRA@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 3, 'MARIA OLIVEIRA', 'MARIA.OLIVEIRA@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 4, 'CARLOS LIMA', 'CARLOS.LIMA@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 5, 'FERNANDA COSTA', 'FER.COSTA@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 6, 'PEDRO SANTOS', 'PEDRO.SANTOS@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 7, 'LUCAS MOURA', 'LUCAS.MOURA@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 8, 'JULIA MARTINS', 'JULIA.MARTINS@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 9, 'RAFAEL ALMEIDA', 'RAFA.ALMEIDA@EMAIL.COM', 'A'
EXECUTE CRUD 'I', 10, 'PRISCILA SOUZA', 'PRI.SOUZA@EMAIL.COM', 'A'

EXECUTE CRUD 'I', 11, NULL, NULL, 'A'

-- SELECT
EXECUTE CRUD 
	@V_OPER = 'S',
	@V_ID_PESSOA = 6,
	@V_NOME = NULL,
	@V_EMAIL = NULL,
	@V_SITUACAO = NULL


-- UPDATE
EXECUTE CRUD 
	@V_OPER = 'A',
	@V_ID_PESSOA = 6,
	@V_NOME = 'PEDRO BISPO',
	@V_EMAIL ='PEDRO.BISPO@EMAIL.COM.BR',
	@V_SITUACAO = NULL

-- DELETE
EXECUTE CRUD 
	@V_OPER = 'D',
	@V_ID_PESSOA = 4,
	@V_NOME = NULL,
	@V_EMAIL = NULL,
	@V_SITUACAO = NULL