-- FUNCAO ESCALAR 

/*
 CRIANDO FUNCAO PARA CONCATENAR NOME E SOBRENOME
*/

-- CRIANDO A FUNCAO
CREATE FUNCTION NOMECOMPLETO(@NOME NVARCHAR(50), @SOBRENOME NVARCHAR(50))
RETURNS NVARCHAR(100)

BEGIN
	RETURN @NOME + ' ' + @SOBRENOME
END

SELECT
	PRIMEIRO_NOME AS NOME,
	ULTIMO_NOME AS SOBRENOME,
	DBO.NOMECOMPLETO(PRIMEIRO_NOME, ULTIMO_NOME) AS NOME_COMPLETO
FROM
 CLIENTE
	
-- DELETANDO A FUNCAO
DROP FUNCTION NOMECOMPLETO