/*
ESTE CÓDIGO SQL REALIZA A ATUALIZAÇÃO DE DADOS DE UMA TABELA USANDO CURSORES.
*/

BEGIN TRY
    -- DECLARANDO VARIÁVEIS
    DECLARE @ID INT
    DECLARE @NOME VARCHAR(20)
    DECLARE @NOTA INT

    DECLARE @DESEMPENHO VARCHAR(20)
    DECLARE @ACIMAMEDIA VARCHAR(3)

    DECLARE @MEDIA DECIMAL(5, 2) = (SELECT SUM(CAST(NOTA AS DECIMAL(5, 2))) / COUNT(NOTA) FROM ALUNOS)

    -- DECLARANDO O CURSOR PARA ACESSAR DADOS DA TABELA ALUNOS (A TABELA DEVE EXISTIR)
    DECLARE MEU_CURSOR CURSOR LOCAL FOR 
        SELECT ID, NOME, NOTA, DESEMPENHO, ACIMAMEDIA FROM ALUNOS 

    OPEN MEU_CURSOR

    FETCH NEXT FROM MEU_CURSOR INTO @ID, @NOME, @NOTA, @DESEMPENHO, @ACIMAMEDIA

    -- FORÇANDO UM ERRO AQUI PARA TESTAR O TRY CATCH:
    -- TENTANDO CONVERTER UM VALOR PARA TIPO INCORRETO PARA FORÇAR UM ERRO
    --SET @NOTA = 'TEXTO'  -- AQUI, ESTAMOS TENTANDO ATRIBUIR UM TEXTO PARA UMA VARIÁVEL DO TIPO INT, O QUE GERARÁ UM ERRO.

    WHILE (@@FETCH_STATUS = 0)
    BEGIN
        IF @NOTA < 5
            SET @DESEMPENHO = 'REPROVADO'
        ELSE IF @NOTA < 6
            SET @DESEMPENHO = 'RECUPERACAO'
        ELSE
            SET @DESEMPENHO = 'APROVADO'

        IF @NOTA > @MEDIA
            SET @ACIMAMEDIA = 'SIM'
        ELSE
            SET @ACIMAMEDIA = 'NAO'

        UPDATE ALUNOS 
        SET DESEMPENHO = @DESEMPENHO,
            ACIMAMEDIA = @ACIMAMEDIA
        WHERE ID = @ID

        FETCH NEXT FROM MEU_CURSOR INTO @ID, @NOME, @NOTA, @DESEMPENHO, @ACIMAMEDIA
    END

    CLOSE MEU_CURSOR
    DEALLOCATE MEU_CURSOR

    PRINT 'MEDIA DA TURMA' + CAST(@MEDIA AS NVARCHAR(10))

    SELECT 
        ID,
        NOME,
        NOTA, 
        DESEMPENHO,
        ACIMAMEDIA
    FROM 
        ALUNOS

END TRY
BEGIN CATCH
    -- CASO OCORRA ERRO, CAPTURA A MENSAGEM E O CÓDIGO DE ERRO
    PRINT 'ERRO OCORRIDO: ' + ERROR_MESSAGE();  -- EXIBINDO A MENSAGEM DE ERRO GERADA PELO SQL SERVER

    -- GARANTINDO QUE O CURSOR SEJA FECHADO CORRETAMENTE, CASO TENHA FALHADO
    IF CURSOR_STATUS('GLOBAL', 'MEU_CURSOR') >= -1
    BEGIN
        CLOSE MEU_CURSOR;
        DEALLOCATE MEU_CURSOR;
    END
END CATCH;
