
-- GERANDO UMA TABUADA COM WHILE

DECLARE @TAB INT = 1
DECLARE @MULTIPLICADO INT
DECLARE @RESULTADO INT

WHILE(@TAB <= 10)
BEGIN
    SET @MULTIPLICADO = 1
    WHILE(@MULTIPLICADO <= 10)
    BEGIN
        SET @RESULTADO = @TAB * @MULTIPLICADO
        PRINT CAST(@TAB AS NVARCHAR) + ' X ' + CAST(@MULTIPLICADO AS NVARCHAR) + ' = ' + CAST(@RESULTADO AS NVARCHAR)
        SET @MULTIPLICADO = @MULTIPLICADO + 1
    END
    SET @TAB = @TAB + 1
END