-- SOMA DE NUMEROS PARES

DECLARE @NUM INT = 1
DECLARE @SOMA INT = 0

WHILE(@NUM <= 1000)
BEGIN
    IF(@NUM % 2 = 0)
        SET @SOMA = @SOMA + @NUM
    SET @NUM = @NUM + 1
END

PRINT 'A SOMA DE TODOS OS NUMEROS PARES DE 1 A 1000 E ' + CAST(@SOMA AS NVARCHAR)