
/*
DESCRIÇÃO:
ESTA FUNÇÃO RECEBE DOIS PARÂMETROS DE DATA (DATA INICIAL E DATA FINAL) E UM INTERVALO EM DIAS.
ELA RETORNA UMA TABELA COM UMA SEQUÊNCIA DE DATAS GERADAS A PARTIR DA DATA INICIAL, INCREMENTANDO CONFORME O INTERVALO INFORMADO, ATÉ ATINGIR OU ULTRAPASSAR A DATA FINAL.

PARÂMETROS:
@DIA - NÚMERO DE DIAS A SER SOMADO A CADA ITERAÇÃO (INTERVALO ENTRE AS DATAS RETORNADAS)
@DTI - DATA INICIAL
@DTF - DATA FINAL

RETORNO:
TABELA COM DUAS COLUNAS:
 - SEQ: NÚMERO SEQUENCIAL INICIANDO EM 1
 - DT: DATAS GERADAS COM BASE NO INTERVALO INFORMADO
*/


CREATE FUNCTION DBO.FUNC_DIAS(@DIA INT, @DTI DATETIME, @DTF DATETIME)

RETURNS @TBL TABLE(SEQ INT, DT DATETIME)
AS

BEGIN

	DECLARE @CONT INT
	SET @CONT = 1

	WHILE @DTI <= @DTF

		BEGIN

			INSERT INTO @TBL (SEQ, DT) VALUES (@CONT, @DTI)

			SET @DTI = DATEADD(DAY, @DIA, @DTI)
			SET @CONT = @CONT + 1

		END

		RETURN

END

SELECT * FROM DBO.FUNC_DIAS(1, GETDATE(), GETDATE() + 12)