/* 
FUNÇÃO QUE RETORNA UMA TABELA COM O NOME DOS MUNICÍPIOS E SUAS RESPECTIVAS POPULAÇÕES,
FILTRANDO PELO ESTADO (UF) INFORMADO COMO PARÂMETRO. OS DADOS SÃO EXTRAÍDOS DA TABELA SENSO.

*/
CREATE FUNCTION FN_CIDADE (@UF VARCHAR(2))
RETURNS TABLE AS
	RETURN(
		SELECT
			A.NOME_MUN,
			A.POPULACAO
		FROM
			SENSO A
		WHERE A.UF = @UF
	)

SELECT * FROM DBO.FN_CIDADE('DF')