/*
PROCEDURE RESPONSÁVEL POR CALCULAR O ÍNDICE DE MASSA CORPORAL (IMC) A PARTIR DO PESO E ALTURA INFORMADOS.
COM BASE NO RESULTADO, RETORNA UMA MENSAGEM CLASSIFICANDO O IMC EM CATEGORIAS COMO: ABAIXO DO PESO, PESO NORMAL, OBESIDADE, ENTRE OUTROS.
*/

CREATE PROCEDURE CALCULO_IMC @PESO DECIMAL(10,2), @ALTURA DECIMAL(10,2)
AS
BEGIN
    DECLARE @IMC DECIMAL(10,2);
    SET @IMC = @PESO / (@ALTURA * @ALTURA);

    IF @IMC < 17
        PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' - MUITO ABAIXO DO PESO'

    ELSE IF @IMC >= 17 AND @IMC <= 18.49
        PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' - ABAIXO DO PESO'

    ELSE IF @IMC >= 18.5 AND @IMC <= 24.99
        PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' - PESO NORMAL'

    ELSE IF @IMC >= 25 AND @IMC <= 29.99
        PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' - ACIMA DO PESO'

    ELSE IF @IMC >= 30 AND @IMC <= 34.99
        PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' - OBESIDADE I'

    ELSE IF @IMC >= 35 AND @IMC <= 39.99
        PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' - OBESIDADE II (SEVERA)'

    ELSE IF @IMC >= 40
        PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' - OBESIDADE III (MÓRBIDA)'

END

-- EXECUTANDO A PROCEDURE
EXEC CALC_IMC 74, 1.75
