


--DISABLE TRIGGER TG_AUD_SAL_V2
--ENABLE TRIGGER TG_AUD_SAL_V2

CREATE TRIGGER TG_AUD_SAL_V2 ON SALARIO
AFTER UPDATE AS
	BEGIN
		
		DECLARE @MATRICULA_AUX INT

		DECLARE CURSOR_PROCESSO CURSOR FOR
			SELECT MATRICULA FROM INSERTED -- TABELA VIRTUAL INSERTED

		OPEN CURSOR_PROCESSO
			FETCH NEXT FROM CURSOR_PROCESSO INTO @MATRICULA_AUX

			WHILE @@FETCH_STATUS = 0
				BEGIN

					INSERT INTO AUDITORIA_SALARIO
						SELECT
							I.MATRICULA,
							D.SALARIO, -- SALARIO ANTIGO
							I.SALARIO, -- SALARIO NOVO
							SYSTEM_USER,
							GETDATE()
						FROM
							DELETED D,
							INSERTED I
						WHERE 1 = 1
							AND D.MATRICULA = I.MATRICULA
							AND @MATRICULA_AUX = I.MATRICULA

						FETCH NEXT FROM CURSOR_PROCESSO INTO @MATRICULA_AUX

				END

				CLOSE CURSOR_PROCESSO

				DEALLOCATE CURSOR_PROCESSO

	END



UPDATE SALARIO SET SALARIO = SALARIO * 1.15

SELECT * FROM AUDITORIA_SALARIO;


